### PR TITLE
How to handle missing and invalid data?

### PR DESCRIPTION
**Pull request by nesokreso**
Add possibility to have empty strings in csv for dataType DATE

### CODE REVIEW

**Comment by arx-deidentifier** [comment]
Thanks for this proposal. What happens when an empty string is provided as a date without this patch? What happens when empty steings are provided for variables of other data types (e.g. Interner, decimal)?

**Comment by nesokreso** [comment]
It throws an exception because an empty String can not be parsed to Date, Integer, Decimal e.g. So with this check it will be converted to a NULL value an the DataSource can be anonymized.

**Comment by prasser** [comment]
I don't think that this is needed, as ARX supports data cleansing during loading. Try this:

Without cleansing:
source.addColumn("Age", DataType.INTEGER);

With cleansing:
source.addColumn("Age", DataType.INTEGER, true);

Does that solve your issue?

**Comment by nesokreso** [comment]
Ok with the cleansing parameter my example runs without exceptions. 
In my opinion it would be nicer, when this is also checked in the parse function. But if you don't want this commit i would close this pull request.

**Comment by prasser** [comment]
IMHO, there are good reasons for _not_ including this in the parse function. An empty string is just one example of an infinite number of invalid values that cannot be parsed. Hence, I see no meaningful reason for including this one example into the parse function, but not others. An addition, how invalid values should be treated is generally a difficult problem (just turning every invalid value into NULL might be problematic, because users might for example need to distinguish between invalid values and missing values). Hence, it makes sense to leave data cleansing to the users and perform it only if explicitly requested. Will close this now,

**Pull request closed without merging**
